GET http://localhost:3000/products

###
GET http://localhost:3000/products/1251

###
POST http://localhost:3000/products/
Content-Type: application/json

{
    "title": "potato",
    "price": 100
}

###
DELETE http://localhost:3000/products/1251

###
PUT http://localhost:3000/products/1251
Content-Type: application/json

{
    "title": "Car",
    "price": 90000
}